language: python

python: "3.6.4"

before_install:
  - touch fake_key.pem
  - mv travis_secrets.yaml secrets.yaml

install:
  - pip3 install homeassistant
  - pip3 install colorlog

script:
  - hass --script check_config --info all