- id: update_available_notification
  alias: "Update Available Notification"
  initial_state: 'on'
  trigger:
    platform: template
    value_template: "{{states('sensor.pypi_hass_version') == states('sensor.current_version') }}"
  action:
    - service: persistent_notification.create
      data:
        title: "Update Available"
        message: >
          Home Assistant {{ states('sensor.pypi_hass_version') }} is available, please update.
        notification_id: "update_available"

- id: change_current_theme
  alias: 'Change Current Theme'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.current_theme
  action:
    - service: frontend.set_theme
      data_template:
        name: "{{states('input_select.current_theme')}}"