homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
    - type: legacy_api_password
      api_password: !secret api_password

  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config

lovelace:
  mode: yaml

hacs:
  token: !secret hacs_github_access_token

#################################################################
#                                                               #
#                           Enables                             #
#                                                               #
#################################################################

hassio:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: https://rosterloh.synology.me:8123
  cors_allowed_origins:
    - https://rosterloh.synology.me
    - 192.168.1.0/24

#default_config
#cloud:
config:
conversation:
discovery:
frontend:
history:
logbook:
map:
mobile_app:
person:
ssdp:
updater:
zeroconf:

google_assistant:
  project_id: !secret google_assistant_project
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light

####################################################
#                                                  #
#                      Logger                      #
#                                                  #
####################################################

logger:
  default: error

####################################################
#                                                  #
#                     Recorder                     #
#                                                  #
####################################################

recorder:
  db_url: !secret recorder_db_url
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    domains:
      - sun