homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.1.0/24
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config

lovelace:
  mode: yaml

hacs:
  token: !secret hacs_github_access_token

hassio:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: https://rosterloh.synology.me:8123
  cors_allowed_origins:
    - https://rosterloh.synology.me
    - 192.168.1.0/24

stream:

#default_config
#cloud:
config:
conversation:
discovery:
frontend:
  themes: !include_dir_merge_named themes
history:
logbook:
map:
mobile_app:
person:
ssdp:
updater:
zeroconf:

google_assistant:
  project_id: !secret google_assistant_project
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - vacuum

logger:
  default: error

recorder:
  db_url: !secret recorder_db_url
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    domains:
      - sun
      - automation