homeassistant:
  customize: !include configuration/customize.yaml
  packages: !include_dir_named packages/
  whitelist_external_dirs:
    - /config

# lovelace:
#   mode: yaml

hassio:

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: https://rosterloh.synology.me:8123
  cors_allowed_origins:
    - https://rosterloh.synology.me
    # - 192.168.1.0/24

stream:

#default_config
#cloud:
config:
conversation:
discovery:
logbook:
map:
mobile_app:
person:
ssdp:
updater:
zeroconf:
safe_mode:
system_health:

shell_command: !include configuration/shell_command.yaml

history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - cover
  exclude:
    entities:
    - sensor.date
    - sensor.time

logger:
  default: error

recorder:
  db_url: !secret recorder_db_url
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    domains:
      - updater
      - automation
      - device_tracker
      - group
      - scene
      - script
    entities:
      - sensor.date
      - sensor.time
      - sun.sun
      - sensor.xiaomi_map
      - zone.home
