homeassistant:
  customize: !include configuration/customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config

lovelace:
  mode: yaml

hacs:
  token: !secret hacs_github_access_token

hassio:

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: https://rosterloh.synology.me:8123
  cors_allowed_origins:
    - https://rosterloh.synology.me
    - 192.168.1.0/24

stream:

#default_config
#cloud:
config:
conversation:
discovery:
frontend:
  themes: !include_dir_named configuration/themes/
logbook:
map:
mobile_app:
person:
ssdp:
updater:
zeroconf:

shell_command: !include configuration/shell_command.yaml

google_assistant:
  project_id: !secret google_assistant_project
  api_key: !secret google_assistant_api_key
  expose_by_default: false
  entity_config:
    sensor.bme680_temperature:
      expose: true
      room: Workshop
    sensor.bme680_humidity:
      expose: true
      room: Workshop
    sensor.workshop_temperature:
      expose: true
      room: Workshop
    sensor.workshop_humidity:
      expose: true
      room: Workshop
    light.aerogarden_plant_leds:
      expose: true
      room: Workshop
    light.wled:
      expose: true
    light.workshop_bulb:
      expose: true
      room: Workshop
    light.workshop_leds:
      expose: true
      room: Workshop
    binary_sensor.workshop_door:
      expose: true
      room: Workshop
    binary_sensor.workshop_presence:
      expose: true
      room: Workshop

history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - cover
  exclude:
    entities:
     - sensor.date
     - sensor.time

logger:
  default: error

recorder:
  db_url: !secret recorder_db_url
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    domains:
      - updater
      - automation
      - device_tracker
      - group
      - scene
      - script
    entities:
      - sensor.date
      - sensor.time
      - sun.sun
      - sensor.xiaomi_map
      - zone.home
