- platform: version
- platform: uptime
  unit_of_measurement: minutes
- platform: speedtest
  hour:
    - 12
  monitored_conditions:
    - download
- platform: command_line
    name: "PyPi HASS Version"
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
- platform: template
    sensors:
      hassuptime:
        friendly_name: "HASS Uptime"
        value_template: >-
          {% set uptime = states.sensor.uptime.state | round %}
          {% set minutes = (uptime % 60) | int %}
          {% set hours = ((uptime / 60) % 24) | int %}
          {% set days = (uptime / 1440) | int %}
          {%- if days > 0 -%}
            {%- if days == 1 -%}
              1 day
            {%- else -%}
              {{ days }} days
            {%- endif -%}
            {{ ', ' }}
          {%- endif -%}
          {{ '%02d' % hours }}:{{ '%02d' % minutes }} hrs

