resources:
  - url: /customcards/custom_ui/tracker-card.js
    type: module
  - url: /customcards/custom_ui/surveillance-card.js
    type: module
  - url: /customcards/custom_ui/mini-graph-card-bundle.js
    type: module
  - url: /customcards/custom_ui/card-modder.js
    type: module
  - url: /customcards/custom_ui/card-tools.js
    type: js
  - url: /customcards/custom_ui/bignumber-card.js
    type: js
  - url: /customcards/custom_ui/compact-custom-header.js
    type: module
  - url: /customcards/custom_ui/weather-card.js
    type: module

#############################################################################################################################################
#                                                                                                                                           # 
#                                                               VIEW - HOME                                                                 #
#                                                                                                                                           #
#############################################################################################################################################  

name: Tun Furlong 
views:
  - id: home
    name: Home
    icon: mdi:home-assistant
    background: center / cover no-repeat url("/local/lovelace/dark.jpg") fixed
    cards:
      - type: custom:compact-custom-header

#################################################################
#                                                               #
#                     Home - Weather Card                       #
#                                                               #
################################################################# 

      - type: vertical-stack
        cards:
          - type: custom:weather-card
            entity: weather.dark_sky
            icons: "/local/custom_ui/icons/"
          - type: glance
            tilte: Aerogarden
            column_width: calc(100% / 4)
            entities:
              - entity: sensor.bme680_temperature
                name: Temperature
              - entity: sensor.bme680_humidity
                name: Humidity
              - entity: sensor.bme680_pressure
                name: Pressure
              - entity: sensor.bme680_gas_resistance
                name: Gas
              - entity: light.plant_lights
                tap_action:
                  action: toggle
              - entity: switch.plant_pump
                tap_action:
                  action: toggle

#################################################################
#                                                               #
#                   Home - OctoPrint Card                       #
#                                                               #
################################################################# 

      - type: picture-entity
        entity: camera.octoprint
        name: printcam
        show_state: false
        tap_action: more-info
        
      - type: horizontal-stack
        cards:
          - type: gauge
            title: Bed Temp
            entity: sensor.prusa_actual_bed_temp
            unit_of_measurement: 째C
            min: 0
            max: 150
            severity: 
              red: 120
              amber: 0
              green: 60
            #scale: '50px'

          - type: gauge
            title: Hot End Temp
            entity: sensor.prusa_actual_tool0_temp
            unit_of_measurement: 째C
            min: 0
            max: 260
            severity:
              red: 225
              amber: 0
              green: 200
            #scale: '50px'  

      - type: horizontal-stack
        cards:
          - type: gauge
            title: Bed Target
            entity: sensor.prusa_target_bed_temp
            unit_of_measurement: 째C
            min: 0
            max: 150
            severity: 
              red: 120
              amber: 0
              green: 59
            #scale: '50px'

          - type: gauge
            title: Hot End Target
            entity: sensor.prusa_target_tool0_temp
            unit_of_measurement: 째C
            min: 0
            max: 260
            severity:
              red: 225
              amber: 0
              green: 199
            #scale: '50px'

      - type: custom:bignumber-card
        title: Current Job Completion Status
        entity: sensor.prusa_job_percentage
        scale: 30px
        from: left
        min: 0
        max: 100
        severity:
          - value: 20
            style: 'var(--label-badge-red)'
          - value: 40
            style: 'var(--label-badge-yellow)'
          - value: 70
            style: 'var(--label-badge-green)' 
      
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Elapsed
            entity: sensor.prusa_time_elapsed
            graph: none

          - type: sensor
            name: Remaining
            entity: sensor.prusa_time_remaining
            graph: none

      - type: glance
        show_header_toggle: false
        column_width: calc(100% / 3)
        entities:
          - entity: binary_sensor.prusa_printing
            name: Printing Status
            icon: mdi:printer-wireless
          - entity: binary_sensor.prusa_printing_error
            name:  Error State
            icon: mdi:printer-alert
          - entity: sensor.prusa_current_state
            name: Current Status

#############################################################################################################################################
#                                                                                                                                           # 
#                                                               VIEW - CCTV                                                                 #
#                                                                                                                                           #
#############################################################################################################################################

  - id: cctv
    name: CCTV
    icon: mdi:cctv
    background: center / cover no-repeat url("/local/lovelace/background-15.gif") fixed
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:surveillance-card
            thumb_interval: 15
            update_interval: 2
            cameras:
              - entity: camera.front_door
                motion_entity: binary_sensor.front_door_camera_path_activity
              - entity: camera.backyard
                motion_entity: binary_sensor.backyard_camera_motion_detected
              - entity: camera.dining_room
                motion_entity: binary_sensor.dining_room_camera_motion_detected
              - entity: camera.octoprint
          - type: custom:compact-custom-header

#############################################################################################################################################
#                                                                                                                                           # 
#                                                               VIEW - SETTINGS                                                             #
#                                                                                                                                           #
#############################################################################################################################################

  - id: settings
    name: Settings
    icon: mdi:settings
    background: center / cover no-repeat url("/local/lovelace/background-15.gif") fixed
    cards:
      - type: custom:compact-custom-header

#################################################################
#                                                               #
#                     Settings - Tracker Card                   #
#                                                               #
#################################################################

      - type: custom:tracker-card
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker

#################################################################
#                                                               #
#                     Settings - Zigbee                         #
#                                                               #
#################################################################

      - type: entities
        entities:
          - entity: input_boolean.zigbee_permit_join
          - entity: timer.zigbee_permit_join
          - entity: sensor.bridge_state
        show_header_toggle: false
        title: Zigbee
