# Custom Card Resources
resources:
  !include lovelace/resources.yaml

# Compact Custom Header
cch:
  menu: hide
  options: hide
  notifications: hide
  voice: hide
  header: false
  chevrons: false
  notify_indicator_color: "#e80000"
  swipe: true
  swipe_wrap: false
  background: 'rgba(0,0,0,0.3)'
  hide_tabs: '5 to 25'
  default_tab: 1

# Decluttering Templates
decluttering_templates:
  !include lovelace/decluttering_templates/decluttering_templates.yaml

# Views
# The following 5 views are swipable, the order
# of these 5 files is the swipe order as well.
# The first view is the page 0. In my setup
# the interface defaults to view 1.
title: Tun Furlong
background: var(--background-image)
views: 
  - !include lovelace/views/climate.yaml
  - !include lovelace/views/main_view.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/devices.yaml
  - !include lovelace/views/security.yaml
# The views below are used as fake popup cards
# They are non swipable and will behave just like
# a popup card or conditional cards. The order of
# these files will not change anything.
  - !include lovelace/views/vacuum.yaml
  - !include lovelace/views/vacuum-zoned-cleaning.yaml
  - !include lovelace/views/alarm.yaml
  - !include lovelace/views/richard.yaml
  - !include lovelace/views/jess.yaml
  - !include lovelace/views/juno.yaml
  - !include lovelace/views/scenes.yaml
  - !include lovelace/views/main_menu.yaml
  - !include lovelace/views/cleaning.yaml
  - !include lovelace/views/floorplan.yaml
  - !include lovelace/views/links.yaml
  - !include lovelace/views/calendar.yaml
  - !include lovelace/views/laundry.yaml
  - !include lovelace/views/energy.yaml
  - !include lovelace/views/other.yaml
  - !include lovelace/views/currently_on.yaml
  - !include lovelace/views/location.yaml
  - !include lovelace/views/themes.yaml
  - !include lovelace/views/weather.yaml

#################################################################
#                                                               #
#                   Home - OctoPrint Card                       #
#                                                               #
################################################################# 

#      - type: vertical-stack
#        cards:
#          - type: picture-entity
#            entity: camera.octoprint
#            name: printcam
#            show_state: false
#            tap_action: more-info
        
#          - type: horizontal-stack
#            cards:
#              - type: gauge
#                title: Bed Temp
#                entity: sensor.prusa_actual_bed_temp
#                unit_of_measurement: 째C
#                min: 0
#                max: 150
#                severity: 
#                  red: 120
#                  amber: 0
#                  green: 60
                #scale: '50px'

#              - type: gauge
#                title: Hot End Temp
#                entity: sensor.prusa_actual_tool0_temp
#                unit_of_measurement: 째C
#                min: 0
#                max: 260
#                severity:
#                  red: 225
#                  amber: 0
#                  green: 200
                #scale: '50px'  

#          - type: horizontal-stack
#            cards:
#              - type: gauge
#                title: Bed Target
#                entity: sensor.prusa_target_bed_temp
#                unit_of_measurement: 째C
#                min: 0
#                max: 150
#                severity: 
#                  red: 120
#                  amber: 0
#                  green: 59
                #scale: '50px'

#              - type: gauge
#                title: Hot End Target
#                entity: sensor.prusa_target_tool0_temp
#                unit_of_measurement: 째C
#                min: 0
#                max: 260
#                severity:
#                  red: 225
#                  amber: 0
#                  green: 199
                #scale: '50px'

#          - type: custom:bignumber-card
#            title: Current Job Completion Status
#            entity: sensor.prusa_job_percentage
#            scale: 30px
#            from: left
#            min: 0
#            max: 100
#            severity:
#              - value: 20
#                style: 'var(--label-badge-red)'
#              - value: 40
#                style: 'var(--label-badge-yellow)'
#              - value: 70
#                style: 'var(--label-badge-green)' 
          
#          - type: horizontal-stack
#            cards:
#              - type: sensor
#                name: Elapsed
#                entity: sensor.prusa_time_elapsed_friendly
#                graph: none
#              - type: sensor
#                name: Remaining
#                entity: sensor.prusa_time_remaining_friendly
#                graph: none
    
#          - type: glance
#            show_header_toggle: false
#            column_width: calc(100% / 3)
#            entities:
#              - entity: binary_sensor.prusa_printing
#                name: Printing Status
#                icon: mdi:printer-wireless
#              - entity: binary_sensor.prusa_printing_error
#                name:  Error State
#                icon: mdi:printer-alert
#              - entity: sensor.prusa_current_state
#                name: Current Status

#################################################################
#                                                               #
#                     Settings - System Card                    #
#                                                               #
#################################################################

#      - type: vertical-stack
#        title: System
#        cards:
#          - type: horizontal-stack
#            cards:
#              - type: custom:mini-graph-card
#                entities:
#                  - sensor.processor_use
#                name: CPU
#                line_color: '#2980b9'
#                line_width: 2
#                hours_to_show: 24
#          - type: vertical-stack
#            cards:
#              - type: custom:bar-card
#                entity: sensor.disk_use_percent_home
#                title: HDD
#                title_position: inside
#                align: split
#                show_icon: true
#                color: '#00ba6a'
#              - type: custom:bar-card
#                entity: sensor.memory_use_percent
#                title: RAM
#                title_position: inside
#                align: split
#                show_icon: true
#              - type: glance
#                entities:
#                  - sensor.count_automations
#                  - sensor.count_lights
#                  - sensor.count_scripts
#                  - sensor.count_sensors
#                  - sensor.count_switches
#              - type: entities
#                entities:
#                  - sensor.last_boot

#################################################################
#                                                               #
#                     Settings - Speed                          #
#                                                               #
#################################################################

#      - type: vertical-stack
#        title: Network
#        cards:
#          - type: horizontal-stack
#            cards:
#              - type: custom:mini-graph-card
#                entities:
#                  - sensor.speedtest_download
#                name: Download
#                line_color: '#2980b9'
#                line_width: 6
#                hours_to_show: 24
#                icon: mdi:download-network
#              - type: custom:mini-graph-card
#                entities:
#                  - sensor.speedtest_upload
#                name: Upload
#                line_color: '#2980b9'
#                line_width: 6
#                hours_to_show: 24
#                icon: mdi:upload-network
#              - type: custom:mini-graph-card
#                entities:
#                  - sensor.speedtest_ping
#                name: Ping
#                line_color: '#dbdfe2'
#                line_width: 6
#                hours_to_show: 24
#                icon: mdi:server-network
