# Custom Card Resources
resources:
  !include lovelace/resources.yaml

# Compact Custom Header
cch:
  !include lovelace/compact-custom-header.yaml

# Decluttering Templates
decluttering_templates:
  !include lovelace/templates/decluttering-templates.yaml

# Views
# The following 5 views are swipable, the order
# of these 5 files is the swipe order as well.
# The first view is the page 0. In my setup
# the interface defaults to view 1.
title: Tun Furlong
background: var(--background-image)
views: 
  - !include lovelace/views/climate.yaml
  - !include lovelace/views/main_view.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/devices.yaml
  - !include lovelace/views/security.yaml
# The views below are used as fake popup cards
# They are non swipable and will behave just like
# a popup card or conditional cards. The order of
# these files will not change anything.
  - !include lovelace/views/vacuum.yaml
  - !include lovelace/views/vacuum-zoned-cleaning.yaml
  - !include lovelace/views/alarm.yaml
  - !include lovelace/views/richard.yaml
  - !include lovelace/views/jess.yaml
  - !include lovelace/views/juno.yaml
  - !include lovelace/views/scenes.yaml
  - !include lovelace/views/main_menu.yaml
  - !include lovelace/views/cleaning.yaml
  - !include lovelace/views/floorplan.yaml
  - !include lovelace/views/links.yaml
  - !include lovelace/views/calendar.yaml
  - !include lovelace/views/laundry.yaml
  - !include lovelace/views/energy.yaml
  - !include lovelace/views/other.yaml
  - !include lovelace/views/currently_on.yaml
  - !include lovelace/views/location.yaml
  - !include lovelace/views/themes.yaml
  - !include lovelace/views/weather.yaml
  - !include lovelace/views/printer.yaml

#################################################################
#                                                               #
#                     Settings - System Card                    #
#                                                               #
#################################################################

#      - type: vertical-stack
#        title: System
#        cards:
#          - type: horizontal-stack
#            cards:
#              - type: custom:mini-graph-card
#                entities:
#                  - sensor.processor_use
#                name: CPU
#                line_color: '#2980b9'
#                line_width: 2
#                hours_to_show: 24
#          - type: vertical-stack
#            cards:
#              - type: custom:bar-card
#                entity: sensor.disk_use_percent_home
#                title: HDD
#                title_position: inside
#                align: split
#                show_icon: true
#                color: '#00ba6a'
#              - type: custom:bar-card
#                entity: sensor.memory_use_percent
#                title: RAM
#                title_position: inside
#                align: split
#                show_icon: true
#              - type: glance
#                entities:
#                  - sensor.count_automations
#                  - sensor.count_lights
#                  - sensor.count_scripts
#                  - sensor.count_sensors
#                  - sensor.count_switches
#              - type: entities
#                entities:
#                  - sensor.last_boot

#################################################################
#                                                               #
#                     Settings - Speed                          #
#                                                               #
#################################################################

#      - type: vertical-stack
#        title: Network
#        cards:
#          - type: horizontal-stack
#            cards:
#              - type: custom:mini-graph-card
#                entities:
#                  - sensor.speedtest_download
#                name: Download
#                line_color: '#2980b9'
#                line_width: 6
#                hours_to_show: 24
#                icon: mdi:download-network
#              - type: custom:mini-graph-card
#                entities:
#                  - sensor.speedtest_upload
#                name: Upload
#                line_color: '#2980b9'
#                line_width: 6
#                hours_to_show: 24
#                icon: mdi:upload-network
#              - type: custom:mini-graph-card
#                entities:
#                  - sensor.speedtest_ping
#                name: Ping
#                line_color: '#dbdfe2'
#                line_width: 6
#                hours_to_show: 24
#                icon: mdi:server-network
