resources: !include lovelace/resources.yaml
custom_header: !include lovelace/custom-header.yaml

title: Tun Furlong
background: var(--background-image)
popup_cards: !include lovelace/templates/legacy_popup_cards.yaml
views: !include_dir_merge_list lovelace/views/