# Custom Card Resources
resources:
  !include lovelace/resources.yaml

# Compact Custom Header
cch:
  !include lovelace/compact-custom-header.yaml

# Decluttering Templates
decluttering_templates:
  !include_dir_named lovelace/templates

# Views
# Files prefixed with a number are swipable.
# The lowest number will always be the first view.
# To hide more/less swipable views configure the 
# views you want to show/hide in the CCH config
title: Tun Furlong
background: var(--background-image)
views:
  !include_dir_merge_list lovelace/views/