resources:
  - url: /community_plugin/surveillance-card/surveillance-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card.js
    type: module
  - url: /community_plugin/bignumber-card/bignumber-card.js
    type: js
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/bar-card/bar-card.js
    type: js
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module

#############################################################################################################################################
#                                                                                                                                           # 
#                                                               VIEW - HOME                                                                 #
#                                                                                                                                           #
#############################################################################################################################################  

name: Tun Furlong
cch:
    menu: show
    options: show
    notifications: clock
    clock_format: '24'
    clock_date: true
    date_locale: en-gb
    swipe: true
views:
  - id: home
    name: Home
    icon: mdi:home-assistant
    background: center / cover no-repeat url("/local/lovelace/dark.jpg") fixed
    cards:

#################################################################
#                                                               #
#                     Home - Presence Card                      #
#                                                               #
################################################################# 

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                show_header_toggle: false
                entities:
                  - sensor.richard
                  - type: divider
                  - sensor.richard_phone_battery
                    
              - type: entities
                show_header_toggle: false
                entities:
                  - sensor.jess
                  - type: divider
                  - sensor.jess_phone_battery

#################################################################
#                                                               #
#                     Home - Weather Card                       #
#                                                               #
################################################################# 

      - type: vertical-stack
        cards:
          - type: custom:weather-card
            entity: weather.dark_sky
            icons: "/local/custom_ui/icons/"
          - type: glance
            tilte: Aerogarden
            column_width: calc(100% / 4)
            entities:
              - entity: sensor.bme680_temperature
                name: Temperature
              - entity: sensor.bme680_humidity
                name: Humidity
              - entity: sensor.bme680_pressure
                name: Pressure
              - entity: sensor.bme680_gas_resistance
                name: Gas
              - entity: light.aerogarden_plant_leds
                tap_action:
                  action: toggle
              - entity: switch.aerogarden_plant_pump
                tap_action:
                  action: toggle
              - entity: input_boolean.aerogarden_leds_automate
                tap_action:
                  action: toggle

#################################################################
#                                                               #
#                   Home - OctoPrint Card                       #
#                                                               #
################################################################# 

      - type: picture-entity
        entity: camera.octoprint
        name: printcam
        show_state: false
        tap_action: more-info
        
      - type: horizontal-stack
        cards:
          - type: gauge
            title: Bed Temp
            entity: sensor.prusa_actual_bed_temp
            unit_of_measurement: 째C
            min: 0
            max: 150
            severity: 
              red: 120
              amber: 0
              green: 60
            #scale: '50px'

          - type: gauge
            title: Hot End Temp
            entity: sensor.prusa_actual_tool0_temp
            unit_of_measurement: 째C
            min: 0
            max: 260
            severity:
              red: 225
              amber: 0
              green: 200
            #scale: '50px'  

      - type: horizontal-stack
        cards:
          - type: gauge
            title: Bed Target
            entity: sensor.prusa_target_bed_temp
            unit_of_measurement: 째C
            min: 0
            max: 150
            severity: 
              red: 120
              amber: 0
              green: 59
            #scale: '50px'

          - type: gauge
            title: Hot End Target
            entity: sensor.prusa_target_tool0_temp
            unit_of_measurement: 째C
            min: 0
            max: 260
            severity:
              red: 225
              amber: 0
              green: 199
            #scale: '50px'

      - type: custom:bignumber-card
        title: Current Job Completion Status
        entity: sensor.prusa_job_percentage
        scale: 30px
        from: left
        min: 0
        max: 100
        severity:
          - value: 20
            style: 'var(--label-badge-red)'
          - value: 40
            style: 'var(--label-badge-yellow)'
          - value: 70
            style: 'var(--label-badge-green)' 
      
      - type: horizontal-stack
        cards:
          - type: sensor
            name: Elapsed
            entity: sensor.prusa_time_elapsed
            graph: none

          - type: sensor
            name: Remaining
            entity: sensor.prusa_time_remaining
            graph: none

      - type: glance
        show_header_toggle: false
        column_width: calc(100% / 3)
        entities:
          - entity: binary_sensor.prusa_printing
            name: Printing Status
            icon: mdi:printer-wireless
          - entity: binary_sensor.prusa_printing_error
            name:  Error State
            icon: mdi:printer-alert
          - entity: sensor.prusa_current_state
            name: Current Status

#################################################################
#                                                               #
#                   Home - Thermostat Card                      #
#                                                               #
#################################################################

      - type: thermostat
        title: Downstairs
        entity: climate.downstairs
        
      - type: custom:mini-graph-card
        entities:
         - entity: sensor.downstairs_thermostat_temperature
           name: TEMPERATURE
           color: '#e74c3c'
         - entity: sensor.downstairs_thermostat_humidity
           name: HUMIDITY
        name: DOWNSTAIRS CLIMATE
        hours_to_show: 36
        points_per_hour: 1

#############################################################################################################################################
#                                                                                                                                           # 
#                                                               VIEW - CCTV                                                                 #
#                                                                                                                                           #
#############################################################################################################################################

  - id: cctv
    name: CCTV
    icon: mdi:cctv
    background: center / cover no-repeat url("/local/lovelace/background-15.gif") fixed
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:surveillance-card
            thumb_interval: 15
            update_interval: 2
            cameras:
              - entity: camera.front_door
                motion_entity: binary_sensor.front_door_camera_path_activity
              - entity: camera.backyard
                motion_entity: binary_sensor.backyard_camera_motion_detected
              - entity: camera.dining_room
                motion_entity: binary_sensor.dining_room_camera_motion_detected
              - entity: camera.octoprint

#############################################################################################################################################
#                                                                                                                                           # 
#                                                               VIEW - SETTINGS                                                             #
#                                                                                                                                           #
#############################################################################################################################################

  - id: settings
    name: Settings
    icon: mdi:settings
    background: center / cover no-repeat url("/local/lovelace/background-15.gif") fixed
    cards:

#################################################################
#                                                               #
#                     Settings - System Card                    #
#                                                               #
#################################################################

      - type: vertical-stack
        title: System
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.processor_use
                name: CPU
                line_color: '#2980b9'
                line_width: 2
                hours_to_show: 24
          - type: vertical-stack
            cards:
              - type: custom:bar-card
                entity: sensor.disk_use_percent_home
                title: HDD
                title_position: inside
                align: split
                show_icon: true
                color: '#00ba6a'
              - type: custom:bar-card
                entity: sensor.memory_use_percent
                title: RAM
                title_position: inside
                align: split
                show_icon: true
              - type: glance
                entities:
                  - sensor.count_automations
                  - sensor.count_lights
                  - sensor.count_scripts
                  - sensor.count_sensors
                  - sensor.count_switches
              - type: entities
                entities:
                  - sensor.last_boot

#################################################################
#                                                               #
#                     Settings - Zigbee                         #
#                                                               #
#################################################################

      - type: vertical-stack
        title: Network
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.speedtest_download
                name: Download
                line_color: '#2980b9'
                line_width: 6
                hours_to_show: 24
                icon: mdi:download-network
              - type: custom:mini-graph-card
                entities:
                  - sensor.speedtest_upload
                name: Upload
                line_color: '#2980b9'
                line_width: 6
                hours_to_show: 24
                icon: mdi:upload-network
              - type: custom:mini-graph-card
                entities:
                  - sensor.speedtest_ping
                name: Ping
                line_color: '#dbdfe2'
                line_width: 6
                hours_to_show: 24
                icon: mdi:server-network
