# Extra Config for Homekit Infused 2020

# Settings that can NOT be set through the UI

# Deep Press (Change to false if you don't need/want deep-press in your setup. Don't use this on iphones without 3d touch!)
deep_press:
  deep_press: false
  
# Supported Features Treshold, Set this to a lower/higher number if it doesn't show a brightness slider on a light-popup.
lights_popup:
  supportedFeaturesTreshold: 9

# Autofill Sorting Method (Choose between: domain, entity_id, name, state, attribute, last_changed last_updated or last_triggered)
lights_sorting:
  method: name
  columns: 3
devices_sorting:
  method: name
  columns: 3
security_binary_sensor_sorting:
  method: name
climate_sensor_sorting:
  method: name
security_camera_sorting:
  method: name
fan_sorting:
  method: name

# Header Advanced
header_secondary:
#  devices: "[[[ if (states['sensor.current_devices_on'].state == 0) return `All devices are off`; if (states['sensor.current_devices_on'].state == 1) return `There is 1 device on`; else return `There are ${states['sensor.current_devices_on'].state} devices on`; ]]]"
#  climate: "[[[ return `The average temperature is ${states['sensor.average_house_temperature'].state}`; ]]]"
#  security: "[[[ if (states['sensor.current_binary_sensors_on'].state == 0) return `All sensors are inactive`; if (states['sensor.current_binary_sensors_on'].state == 1) return `There is 1 sensor active`; else return `There are ${states['sensor.current_lights_on'].state} sensors active`; ]]]"
#  automations:
#  battery:
#  calendar:
#  cleaning:
#  computers: "[[[ if (states['sensor.current_computers_on'].state == 0) return `All computers are off`; if (states['sensor.current_computers_on'].state == 1) return `Er is 1 computer ingeschakeld`; else return `Er zijn ${states['sensor.current_lights_on'].state} computers ingeschakeld`; ]]]"
#  energy:
#  floorplan:
#  laundry:
#  location: "[[[ if (states['group.device_status'].state == 'home') return `There is no-one home`; else return `Everyone is away`; ]]]"
#  media:
#  scenes:
#  system:
#  traffic:
#  vacuum: "[[[ return `Status: ${states['vacuum.xiaomi_vacuum_cleaner'].state}`; ]]]"
#  weather: "[[[ return `${states['sensor.dark_sky_hourly_summary'].state}`; ]]]"
#  menu:
#  alarm: "[[[ if (states['alarm_control_panel.home_alarm'].state == 'disarmed') return `The alarm is disarmed`; else return `The alarm is armed`; ]]]"
#  download:
#  lights: "[[[ if (states['sensor.current_lights_on'].state == 0) return `All lights are off`; if (states['sensor.current_lights_on'].state == 1) return `There is 1 light on`; else return `There are ${states['sensor.current_lights_on'].state} lights on`; ]]]"
#  custom_a:
#  custom_b:
#  custom_c:
#  custom_d:
