# lovelace_gen

- title: Automations
  path: automations
  icon: mdi:auto-fix
  cards:   
    - type: vertical-stack
      cards:
        - type: custom:state-switch
          entity: input_boolean.header_advanced_mode_automation
          states:
            "off":
              !include
              - '../templates/system_header.yaml'
              - name: input_text.name_header_secondary_automations
                system_header: input_boolean.header_secondary_automation
                icon: "[[[ return `${states['input_text.icon_header_automations'].state}` ]]]"
                {% raw %}
                content: "{{ states.input_text.name_header_automations.state }}"
                {% endraw %}
            "on":
              !include
              - '../templates/system_header_advanced.yaml'
              - name: "{{ _global.header_secondary.automations|default('return `Set your own template in YAML`') }}"
                system_header: input_boolean.header_secondary_automation
                icon: "[[[ return `${states['input_text.icon_header_automations'].state}` ]]]"
{% raw %}
                content: "{{ states.input_text.name_header_automations.state }}"
        - type: conditional
          conditions:
            - entity: input_boolean.edit_mode
              state: "on"
          card:
            !include
            - '../templates/edit_mode_warning.yaml'
            - template: automation_layout_popup.yaml
        - type: conditional
          conditions:
            - entity: input_boolean.automations_automations
              state: "on"
          card:
            type: horizontal-stack
            cards:
              - !include ../includes/blank-card.yaml
              - type: custom:layout-card
                cards:
                  - type: custom:auto-entities
                    filter:
                      include:
                        - domain: automation
                    sort:
                      method: name
                      numeric: true
                    card:
                      type: entities
                      style: |
                        ha-card {
                          border-radius: {{ states('input_select.border_radius') }};
                          box-shadow: {{ states('input_select.box_shadow') }};
                        }
              - !include ../includes/blank-card.yaml
        - type: conditional
          conditions:
            - entity: input_boolean.user_content_message
              state: "on"
          card:
            type: horizontal-stack
            cards:
              - !include ../includes/blank-card.yaml
              - type: custom:layout-card
                cards:
                  - !include ../includes/edit_mode/message-user-content-edit-mode.yaml
              - !include ../includes/blank-card.yaml
        - type: conditional
          conditions:
            - entity: input_boolean.automations_user_content
              state: "on"
          card:
            type: horizontal-stack
            cards:
              - !include ../includes/blank-card.yaml
              - type: custom:layout-card
                cards:
                  !include ../../user_content/views/automations_user_content.yaml
              - !include ../includes/blank-card.yaml
{% endraw %}