# lovelace_gen

- title: {{ _global.security_header.title|default('Security') }}
  path: security
  icon: {{ _global.security_header.icon|default('mdi:alert') }}
  cards:
    - type: vertical-stack
      cards:
        - !include
          - '../templates/system_header.yaml'
          - name: "[[[ if (states['alarm_control_panel.home_alarm'].state == 'disarmed') return `The alarm is disarmed!`; else return `The alarm is armed!` ]]]"
            icon: {{ _global.security_header.icon|default('mdi:alert') }}
            content: {{ _global.security_header.title|default('Security') }}
        - !include
          - '../templates/auto_fill_camera_template.yaml'
          - content: {{ _global.security.camera_category_name|default('Camera`s') }}
            group: group.all_cameras
        - !include
          - '../templates/auto_fill_security_template.yaml'
          - content: {{ _global.security.door_category_name|default('Doors') }}
            group: group.all_door_sensors
        - !include
          - '../templates/auto_fill_security_template.yaml'
          - content: {{ _global.security.window_category_name|default('Windows') }}
            group: group.all_window_sensors
        - !include
          - '../templates/auto_fill_security_template.yaml'
          - content: {{ _global.security.motion_category_name|default('Motion') }}
            group: group.all_motion_sensors
        - !include
          - '../templates/auto_fill_security_template.yaml'
          - content: {{ _global.security.other_category_name|default('Other') }}
            group: group.all_smoke_detectors
