title: Security
path: security
cards:
  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: back_button
        variables:
          - name1: Alarm
          - icon1: shield-home
          - path1: alarm
      - type: custom:decluttering-card
        template: header_text
        variables:
          - content: '## Security'
      - type: custom:decluttering-card
        template: header_text
        variables:
          - content: "##### Camera's"
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.front_door
            title: Camera's  
            aspect_ratio: 16x9
          - !include ../includes/blank-card.yaml
      - type: horizontal-stack
        cards:
          - !include ../includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.backyard
            title: Camera's
            aspect_ratio: 16x9
          - !include ../includes/blank-card.yaml

### The following piece is for tablets only.
  - type: custom:state-switch
    entity: user
    states:
      Home Assistant:
        type: vertical-stack
        cards:
          - type: markdown 
            style: |
              ha-card {
                background: none;
                color: white;
                box-shadow: none;
                text-align: end;
                font-size: 45px;
                height: 155px;
              }
            content: '# [[ sensor.time.state ]]'
### End of tablet code.

#  - type: vertical-stack
#    cards:
#      - type: custom:decluttering-card
#        template: header_text
#        variables:
#          - content: '##### Doors'
#      - type: horizontal-stack
#        cards:
#          - !include ../includes/blank-card.yaml
#          - type: custom:decluttering-card
#            template: switch_button_card
#            variables:
#              - entity: binary_sensor.door_window_sensor_158d000236f9dd
#              - name: Voordeur
#              - icon: door
#              - show_last_changed: true
#              - tap_action: more-info
#              - variable: icon
#              - spin: 'mdi:door-open'
#          - type: custom:decluttering-card
#            template: switch_button_card
#            variables:
#              - entity: binary_sensor.door_window_sensor_158d000238644b
#              - name: Woonkamer
#              - icon: door
#              - show_last_changed: true
#              - tap_action: more-info
#              - variable: icon
#              - spin: 'mdi:door-open'
#          - type: custom:decluttering-card
#            template: switch_button_card
#            variables:
#              - entity: binary_sensor.door_window_sensor_158d000232ac1b
#              - name: Slaapkamer
#              - icon: door
#              - show_last_changed: true
#              - tap_action: more-info
#              - variable: icon
#              - spin: 'mdi:door-open'
#          - !include ../includes/blank-card.yaml
#      - type: custom:decluttering-card
#        template: header_text
#        variables:
#          - content: '##### Motion'
#      - type: horizontal-stack
#        cards:
#          - !include ../includes/blank-card.yaml
#          - type: custom:decluttering-card
#            template: switch_button_card
#            variables:
#              - entity: binary_sensor.dafang_motion_sensor
#              - name: Gallerij
#              - icon: motion-sensor
#              - show_last_changed: true
#              - tap_action: more-info
#          - type: custom:decluttering-card
#            template: switch_button_card
#            variables:
#              - entity: binary_sensor.motion_sensor_158d0002b7eec9
#              - name: Bijkeuken
#              - icon: motion-sensor
#              - show_last_changed: true
#              - tap_action: more-info
#          - type: custom:decluttering-card
#            template: switch_button_card
#            variables:
#              - entity: binary_sensor.motion_sensor_158d00024e687d
#              - name: Toilet
#              - icon: motion-sensor
#              - show_last_changed: true
#              - tap_action: more-info
#          - !include ../includes/blank-card.yaml
#      - type: custom:decluttering-card
#        template: header_text
#        variables:
#          - content: '##### Alarms'
#      - type: horizontal-stack
#        cards:
#          - !include ../includes/blank-card.yaml
#          - type: custom:decluttering-card
#            template: switch_button_card
#            variables:
#              - entity: binary_sensor.smoke_sensor_158d000287ab41
#              - name: Rookmelder
#              - icon: smoke-detector
#              - show_last_changed: true
#              - tap_action: more-info
#          - type: 'custom:button-card'
#            color_type: blank-card
#            aspect_ratio: 1/1
#          - type: 'custom:button-card'
#            color_type: blank-card
#            aspect_ratio: 1/1
#          - !include ../includes/blank-card.yaml
      - !include ../includes/bottom-card.yaml