#################################################################
#                                                               #
#                      Packages/Weather                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  sun:
    name: Sun
    view: no
    entities:
      - sun.sun
      - sensor.moon

#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                 Sensor - AirVisual               #
#                                                  #
####################################################

  - platform: airvisual
    api_key: !secret airviskey
    monitored_conditions:
      - us
    show_on_map: false
    scan_interval: 600
    city: london
    state: england
    country: uk

####################################################
#                                                  #
#                  Sensor - Darksky                #
#                                                  #
####################################################

  - platform: darksky
    api_key: !secret darksky_key
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - summary
      - temperature
      - humidity
      - pressure
      - apparent_temperature
      - precip_probability
      - icon
      - precip_intensity
      - precip_accumulation
      - dew_point
      - wind_speed
      - wind_gust
      - wind_bearing
      - cloud_cover
      - visibility
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - moon_phase
      - sunrise_time
      - sunset_time
      - ozone
      - precip_type

####################################################
#                                                  #
#                   Sensor - Moon                  #
#                                                  #
####################################################

  - platform: moon

####################################################
#                                                  #
#                 Sensor - Season                  #
#                                                  #
####################################################

  - platform: season
    type: astronomical
    
#################################################################
#                                                               #
#                              Sun                              #
#                                                               #
#################################################################

sun:

#################################################################
#                                                               #
#                            Weather                            #
#                                                               #
#################################################################

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily
