# lovelace_gen

# card
type: custom:button-card
style: |
  ha-card {
    margin-top: -17px;
  }
name: Tap to go back to the Settings
icon: mdi:arrow-left-circle
deep_press: {{ _global.deep_press.deep_press|default('false') }}
size: 25%
aspect_ratio: 11/1
entity: input_boolean.edit_mode
show_name: true
show_icon: false
show_state: false
show_label: false
show_last_changed: false
tap_action:
  action: navigate
  navigation_path: /lovelace/settings
  haptic: light
hold_action:
  action: navigate
  navigation_path: /lovelace/settings
  haptic: heavy
styles:
  card:
    - border-radius: 0px
    - --ha-card-background: {{ background_color|default('Crimson') }}
    - box-shadow: none
  img_cell:
    - align-self: start
    - text-align: start
    - margin-right: {{ margin_right|default('60px') }}
  name:
    - justify-self: center
    - font-weight: bold
    - font-family: "[[[ return states['input_text.font_family'].state ]]]" 
    - font-size: "[[[ return states['input_select.name_font_size_selector'].state ]]]"
    - color: white
state:
  - value: "on" 
    styles:
      card:
        - --ha-card-background: {{ background_color|default('Crimson') }}
        - opacity: 1.0
      name:
        - color: white
      icon:
        - color: white