#################################################################
#                                                               #
#                      Packages/Cleaning                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Input Select                            #
#                                                               #
#################################################################

input_select:
  dishwasher_status:
    name: Dishwasher Status
    options:
      - Idle
      - Running
      - Drying
      - Clean
      - Power OFF
    initial: Idle
  washing_machine_status:
    name: Washing Machine Status
    options:
      - Idle
      - Running
      - Finishing
      - Clean
      - Power OFF
    initial: Idle

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                  Template                        #
#                                                  #
####################################################

  - platform: template
    sensors:
      washing_machine_status:
        value_template: '{{ states.input_select.washing_machine_status.state}}'
        friendly_name: 'Washing Machine Status'
      dishwasher_status:
        value_template: '{{ states.input_select.dishwasher_status.state}}'
        friendly_name: 'Dishwasher Status'