#################################################################
#                                                               #
#                     Packages/Date & Time                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            Binary Sensors - Workday              #
#                                                  #
#################################################### 

  - platform: workday
    country: UK
    workdays: [mon, tue, wed, thu, fri]
    
#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Sensor - Time/Date                #
#                                                  #
####################################################

  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - date_time_iso
      - time_date
      - time_utc
      - beat

####################################################
#                                                  #
#                Sensor - Template                 #
#                                                  #
####################################################

  - platform: template
    sensors:
      time_template:
        value_template: >-
          {% if (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 %}
            Good Evening
          {% elif (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
            Good Morning
          {% elif (states.sun.sun.attributes.elevation) < -4 %}
            Good Night
          {% else %}
            Good Day
          {% endif %}  