#################################################################
#                                                               #
#                     Packages/Date & Time                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:

####################################################
#                                                  #
#            Binary Sensors - Workday              #
#                                                  #
#################################################### 

  - platform: workday
    country: UK
    workdays: [mon, tue, wed, thu, fri]
    
#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                Sensor - Time/Date                #
#                                                  #
####################################################

  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - date_time_iso
      - time_date
      - time_utc
      - beat