#################################################################
#                                                               #
#                      Packages/Firmware                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                        Input Boolean                          #
#                                                               #
#################################################################

input_boolean:        
  ha_update_available:
    name: HA Update Avaiable
    initial: off
    icon: mdi:cloud-download

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                  HASSIO Version                  #
#                                                  #
####################################################

## Check Latest HA Version
  - platform: rest
    resource: https://s3.amazonaws.com/hassio-version/stable.json
    name: Latest HA Version
    value_template: "{{ value_json.homeassistant.raspberrypi3-64 }}"
    scan_interval: 3600
## Remote    
  - platform: version
    image: raspberrypi3-64
    source: hassio
## Local 
  - platform: version

#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:
  
  - alias: Update notifications
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: updater.updater
    action:
    - service: notify.slack
      data:
        title: 'Home Assistant Update'
        message: "New Home Assistant version {{ states.updater.updater.state }} is available for download.\r\n\r\nYou are currently running {{ sensor.current_version }}.\r\n\r\nhttps://home-assistant.io/blog/categories/release-notes/"