#################################################################
#                                                               #
#                      Packages/Media Player                    #
#                                                               #
#################################################################

media_player:

  - platform: androidtv
    host: !secret shield
    name: "ShieldTV"
    adb_server_ip: !secret hass
    adb_server_port: 5038
    apps:
      "amazon": "Amazon Prime Video"
      "youtube": "Youtube"
      "netflix": "Netflix"
      
  - platform: webostv
    host: !secret lg_tv
    name: Living Room TV
    filename: webostv.conf
    timeout: 5

#################################################################
#                                                               #
#                            Scenes                             #
#                                                               #
#################################################################

scene:

  - name: Livingroom dim
    entities:
      light.dimmable_light_1:
        state: on
        transition: 5
        brightness_pct: 0
      light.dimmable_light_2:
        state: on
        transition: 5
        brightness_pct: 0
      light.dimmable_light_3:
        state: on
        transition: 5
        brightness_pct: 15
        color_temp: 280
      light.dimmable_light_4:
        state: on
        transition: 5
        brightness_pct: 0
      light.dimmable_light_5:
        state: on
        transition: 5
        brightness_pct: 0
      light.dimmable_light_6:
        state: on
        transition: 5
        brightness_pct: 0
      light.dimmable_light_7:
        state: on
        transition: 5
        brightness_pct: 15
        color_temp: 280
      light.dimmable_light_8:
        state: on
        transition: 5
        brightness_pct: 0

#################################################################
#                                                               #
#                            Groups                             #
#                                                               #
#################################################################

group:

  living_room_overhead:
    name: Livingroom Overhead Lights
    entities:
      - light.dimmable_light_1
      - light.dimmable_light_2
      - light.dimmable_light_3
      - light.dimmable_light_4
      - light.dimmable_light_5
      - light.dimmable_light_6
      - light.dimmable_light_7
      - light.dimmable_light_8

#################################################################
#                                                               #
#                         Automation                            #
#                                                               #
#################################################################

automation:

  - alias: 'Dim Lights for Lounge Media'
    initial_state: 'true'
    trigger:
    - entity_id: media_player.shieldtv
      platform: state
      from: 'off'
      to: 'standby'
    condition:
      condition: or
      conditions:
        - after: sunset
          condition: sun
          after_offset: "-01:00:00"
        - before: sunrise
          condition: sun
    action:
    - service: scene.turn_on
      data:
        entity_id: scene.livingroom_dim

  - alias: 'Lounge Lights on when TV off'
    initial_state: 'true'
    trigger:
    - entity_id: media_player.shieldtv
      platform: state
      from: 'standby'
      to: 'off'
    condition:
      condition: or
      conditions:
        - after: sunset
          condition: sun
          after_offset: "-01:00:00"
        - before: sunrise
          condition: sun
    action:
    - service: light.turn_on
      data:
        entity_id: light.living_room
        transition: 3
        brightness_pct: 60