badnest:
  issue_token: !secret nest_issue_token
  cookie: !secret nest_cookie
  region: eu

climate:
  - platform: badnest
    scan_interval: 10

camera:
  - platform: badnest

sensor:
  - platform: badnest