#################################################################
#                                                               #
#                    Packages/Theme Control                     #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                         Input Select                          #
#                                                               #
#################################################################

input_select:

  theme_selector:
    name: Theme Selector 
    options:
      - Silver
      - Space Gray
      - Disable
      - Auto

#################################################################
#                                                               #
#                          Automations                          #
#                                                               #
#################################################################

automation:
  # Theme Selector
  - alias: 'themes'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sun.sun
    action:
      - service: frontend.set_theme
        data_template:
          name: >
            {% if is_state('input_select.theme_selector', 'Silver') %}
              Silver
            {% elif is_state('input_select.theme_selector', 'Space Gray') %}
              Space Gray
            {% elif is_state('input_select.theme_selector', 'Disable (use theme per user)') %}
              Disable
            {% elif (is_state('sun.sun', 'above_horizon')) and (is_state('input_select.theme_selector', 'Auto'))  %}
              Silver
            {% elif (is_state('sun.sun', 'below_horizon')) and (is_state('input_select.theme_selector', 'Auto'))  %}
              Space Gray
            {% elif is_state('input_select.theme_selector', 'Auto') %}
              Space Gray
            {% endif %}