#################################################################
#                                                               #
#                    Packages/Theme Control                     #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                         Input Select                          #
#                                                               #
#################################################################

input_select:
  theme_selector:
    name: Theme Selector 
    options:
      - Homekit Blue Light
      - Homekit Blue Dark
      - Homekit Gray Light
      - Homekit Gray Dark
      - Homekit Orange
      - Standard Blue Light
      - Standard Blue Dark
      - Standard Gray Light
      - Standard Gray Dark
      - Standard Orange
      - Automatic (default)
    initial: Automatic (default)
    
#################################################################
#                                                               #
#                          Automations                          #
#                                                               #
#################################################################

automation:
  - alias: 'Set theme light at startup'
    initial_state: 'true'
    trigger:
      - platform: homeassistant
        event: start
    condition:
      condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    action:
      service: frontend.set_theme
      data:
        name: Homekit Gray Light

  - alias: 'Set theme dark at startup'
    initial_state: 'true'
    trigger:
      - platform: homeassistant
        event: start
    condition:
      condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    action:
      - service: frontend.set_theme
        data:
          name: Homekit Gray Dark

  - alias: 'theme selector input_select 1'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
        to: 'Homekit Gray Light'
    action:
      - service: frontend.set_theme
        data:
          name: Homekit Gray Light
      - service: homeassistant.turn_off
        data:
          entity_id: group.theme_selector
  - alias: 'theme selector input_select 2'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
        to: 'Homekit Gray Dark'
    action:
      - service: frontend.set_theme
        data:
          name: Homekit Gray Dark
      - service: homeassistant.turn_off
        data:
          entity_id: group.theme_selector
  - alias: 'theme selector input_select 3'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
        to: 'Homekit Blue Light'
    action:
      - service: frontend.set_theme
        data:
          name: Homekit Blue Light
      - service: homeassistant.turn_off
        data:
          entity_id: group.theme_selector
  - alias: 'theme selector input_select 4'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
        to: 'Homekit Blue Dark'
    action:
      - service: frontend.set_theme
        data:
          name: Homekit Blue Dark
      - service: homeassistant.turn_off
        data:
          entity_id: group.theme_selector
  - alias: 'theme selector input_select 5'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
        to: 'Standard Blue Light'
    action:
      - service: frontend.set_theme
        data:
          name: Standard Blue Light
      - service: homeassistant.turn_off
        data:
          entity_id: group.theme_selector
  - alias: 'theme selector input_select 6'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
        to: 'Standard Blue Dark'
    action:
      - service: frontend.set_theme
        data:
          name: Standard Blue Dark
      - service: homeassistant.turn_off
        data:
          entity_id: group.theme_selector
  - alias: 'theme selector input_select 7'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
        to: 'Automatic (default)'
    action:
      - service: frontend.set_theme
        data:
          name: Homekit Gray Dark
      - service: homeassistant.turn_off
        data:
          entity_id: group.theme_selector
  - alias: 'theme selector input_select 8'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
        to: 'Standard Gray Light'
    action:
      - service: frontend.set_theme
        data:
          name: Standard Gray Light
      - service: homeassistant.turn_off
        data:
          entity_id: group.theme_selector
  - alias: 'theme selector input_select 9'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
        to: 'Standard Gray Dark'
    action:
      - service: frontend.set_theme
        data:
          name: Standard Gray Dark
      - service: homeassistant.turn_off
        data:
          entity_id: group.theme_selector
  - alias: 'theme selector input_select 10'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
        to: 'Homekit Orange'
    action:
      - service: frontend.set_theme
        data:
          name: Homekit Orange
      - service: homeassistant.turn_off
        data:
          entity_id: group.theme_selector
  - alias: 'theme selector input_select 11'
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
        to: 'Standard Orange'
    action:
      - service: frontend.set_theme
        data:
          name: Standard Orange
      - service: homeassistant.turn_off
        data:
          entity_id: group.theme_selector
  # Theme Day/Night Cycle
  - alias: 'Set dark theme for the night'
    initial_state: true
    trigger:
      - platform: sun
        event: sunset
        offset: '+00:00:00'
    action:
      - service: frontend.set_theme
        data:
          name: Homekit Gray Dark
  - alias: 'Set light theme for the day'
    initial_state: true
    trigger:
      - platform: sun
        event: sunrise
        offset: '+00:00:00'
    action:
      - service: frontend.set_theme
        data:
          name: Homekit Gray Light