#################################################################
#                                                               #
#                         Packages/Travel                       #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                   UK Transport                   #
#                                                  #
####################################################

  - platform: uk_transport
    app_id: !secret uk_transport_app
    app_key: !secret uk_transport_secret
    queries:
      - mode: train
        origin: TRI
        destination: EUS
      - mode: train
        origin: EUS
        destination: TRI

####################################################
#                                                  #
#                 Waze Travel Time                 #
#                                                  #
####################################################

  - platform: waze_travel_time
    name: Travel Time Jess to Home
    origin: person.jess
    destination: zone.home
    region: 'EU'

####################################################
#                                                  #
#                  Template                        #
#                                                  #
####################################################

#  - platform: template
#    sensors:
#      next_train_status:
#        friendly_name: 'Next train status'
#        value_template: '{{state_attr('sensor.next_train_to_eus', 'next_trains')[0].status}}'
#      next_trains_origin:
#        friendly_name: 'Next train origin'
#        value_template: '{{state_attr('sensor.next_train_to_eus', 'next_trains')[0].origin_name}}'
#      next_trains_estimated:
#        friendly_name: 'Next train estimated'
#        value_template: '{{state_attr('sensor.next_train_to_eus', 'next_trains')[0].estimated}}'
#      next_trains_scheduled:
#        friendly_name: 'Next train scheduled'
#        value_template: '{{state_attr('sensor.next_train_to_eus', 'next_trains')[0].scheduled}}'
#      next_trains_platform:
#        friendly_name: 'Next train platform'
#        value_template: '{{state_attr('sensor.next_train_to_eus', 'next_trains')[0].platform}}'
