#################################################################
#                                                               #
#                           Packages/UI                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                         Input Boolean                         #
#                                                               #
#################################################################

input_boolean:
  # Other
  dummy1:
    initial: off
  dummy2:
    initial: off
  # Scenes
  scene_day_lights:
  scene_night_lights:
  scene_evening_lights:
  scene_cleaning:
  scene_near_bed:
  scene_washing:
  scene_finished_washing:
  scene_cooking:
  scene_finished_cooking:
  scene_goodnight:
  scene_lights_out:
  # Frontpage Alarm Button
  simple_alarm:
  # Notification input_booleans
  notification_bedroom_door:
  notification_front_door:
  notification_livingroom_door:
  notification_washing_machine:
  notification_dishwasher:
  notification_alarm:
  notification_all_calm:
  notification_smoke_detector:
  notification_juno:
  notification_motion_outside:
  notification_motion_toilet:
  notification_motion_workshop:
  notification_vacuum:
  notification_anniversary:
  notification_birthday:
  notification_motion_hall:
  notification_current_lights:
  notification_current_devices:
  notification_current_radiators:
  notification_current_sensors:

#################################################################
#                                                               #
#                         Input Select                          #
#                                                               #
#################################################################

input_select:
  # Border Radius used in border-radius templates,
  # you can adjust border size to be selected here
  border_radius:
    name: Border Radius
    options:
      - 0px
      - 6px
      - 12px
      - 18px

  # Border Radius selector to show in the interface
  border_radius_selector:
    name: Border Radius Selector
    options:
      - None 
      - Small
      - Standard
      - Large

  # Quick Access Menu Border Radius used in border-radius
  # templates, you can adjust border size to be selected here
  qam_border_radius:
    name: Quick Access Menu Border Radius
    options:
      - 0px
      - 3px
      - 6px
      - 9px

  # Quick Access Menu Border Radius selector to show in the interface
  qam_border_radius_selector:
    name: Quick Access Menu Border Radius Selector
    options:
      - None
      - Small
      - Standard
      - Large

  # Box Shadow used in box-shadow templates, you can adjust
  # how the box shadow looks in here
  box_shadow:
    name: Box Shadow
    options:
      - none
      - 1px 1px 1px 0px rgba(0,0,0,0.75)
      - 2px 2px 2px 0px rgba(0,0,0,0.75)
      - 3px 3px 3px 0px rgba(0,0,0,0.75)
      - 5px 5px 5px 0px rgba(0,0,0,0.75)
      - 7px 7px 7px 0px rgba(0,0,0,0.75)
  
  # Box Shadow selector to show in the interface
  box_shadow_selector:
    name: Box Shadow Selector
    options:
      - None
      - Small
      - Standard
      - Medium
      - Large
      - Huge

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                  Template                        #
#                                                  #
####################################################

  - platform: template
    sensors:
      current_lights_on:
        friendly_name: All Lights Currently On
        unit_of_measurement: 'On'
        value_template: >
          {% set total = 0 %}
          {% if is_state('light.aerogarden_plant_leds', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.workshop_leds', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.workshop_bulb', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.dimmable_light_1', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.dimmable_light_2', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.dimmable_light_3', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.dimmable_light_4', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.dimmable_light_5', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.dimmable_light_6', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.dimmable_light_7', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.dimmable_light_8', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.hallway', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.front_door', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.kitchen_table', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('light.living_room_lamp', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {{total}}
  # Template All Devices
  - platform: template
    sensors:
      current_devices_on:
        friendly_name: All Devices Currently On
        unit_of_measurement: 'On'
        value_template: >
          {% set total = 0 %}
          {% if is_state('switch.prusa_printer', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('switch.aerogarden_plant_pump', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {{total}}
  # Template All Sensors
  - platform: template
    sensors:
      current_sensors_on:
        friendly_name: All Sensors Currently On
        unit_of_measurement: 'On'
        value_template: >
          {% set total = 0 %}
          {% if is_state('binary_sensor.backyard_camera_motion_detected', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.backyard_camera_person_detected', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.clip_sensor_toogle_on_off', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.front_door_camera_motion_detected', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.in_bed', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.jess_phone_charging', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.richard_phone_charging', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.window_door_sensor', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.workshop_door', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.workshop_motion_motion', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('binary_sensor.workshop_presence', 'on') %}
            {% set total = total + 1 %}
          {% endif %}
          {{total}}
  # Template All Radiator Valves
  - platform: template
    sensors:
      current_radiator_valves_on:
        friendly_name: All Radiator Valves Currently On
        unit_of_measurement: 'On'
        value_template: >
          {% set total = 0 %}
          {% if is_state('climate.tado_smart_radiator_thermostat_va1671957504', 'heat') %}
            {% set total = total + 1 %}
          {% endif %}
          {% if is_state('climate.tado_smart_radiator_thermostat_va2898201344', 'heat') %}
            {% set total = total + 1 %}
          {% endif %}
          {{total}}

#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:

  # Border Radius Selector
  - alias: input select beautifier box-shadow
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: input_select.box_shadow_selector
    action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.box_shadow
        option: >
          {% if is_state('input_select.box_shadow_selector', 'None') %}
            none
          {% elif is_state('input_select.box_shadow_selector', 'Small') %}
            1px 1px 1px 0px rgba(0,0,0,0.75)
          {% elif is_state('input_select.box_shadow_selector', 'Standard') %}
            2px 2px 2px 0px rgba(0,0,0,0.75)
          {% elif is_state('input_select.box_shadow_selector', 'Medium') %}
            3px 3px 3px 0px rgba(0,0,0,0.75)
          {% elif is_state('input_select.box_shadow_selector', 'Large') %}
            5px 5px 5px 0px rgba(0,0,0,0.75)
          {% elif is_state('input_select.box_shadow_selector', 'Huge') %}
            7px 7px 7px 0px rgba(0,0,0,0.75)
          {% endif %}

  # Border Radius Selector
  - alias: input select beautifier border-radius
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: input_select.border_radius_selector
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.border_radius
        option: >
          {% if is_state('input_select.border_radius_selector', 'None') %}
            0px
          {% elif is_state('input_select.border_radius_selector', 'Small') %}
            6px
          {% elif is_state('input_select.border_radius_selector', 'Standard') %}
            12px
          {% elif is_state('input_select.border_radius_selector', 'Large') %}
            18px
          {% endif %}

  # Quick Access Menu Border Radius Selector
  - alias: input select beautifier qam border-radius
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: input_select.qam_border_radius_selector
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.qam_border_radius
        option: >
          {% if is_state('input_select.qam_border_radius_selector', 'None') %}
            0px
          {% elif is_state('input_select.qam_border_radius_selector', 'Small') %}
            3px
          {% elif is_state('input_select.qam_border_radius_selector', 'Standard') %}
            6px
          {% elif is_state('input_select.qam_border_radius_selector', 'Large') %}
            9px
          {% endif %}
