#################################################################
#                                                               #
#                           Packages/UI                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                         Input Boolean                         #
#                                                               #
#################################################################

input_boolean:
  dummy1:
    initial: off
  dummy2:
    initial: off
  scene_day_lights:
  scene_night_lights:
  scene_evening_lights:
  scene_cleaning:
  scene_near_bed:
  scene_washing:
  scene_finished_washing:
  scene_cooking:
  scene_finished_cooking:
  scene_goodnight:
  scene_lights_out:
  simple_alarm:
  notification_bedroom_door:
  notification_front_door:
  notification_livingroom_door:
  notification_washing_machine:
  notification_dishwasher:
  notification_alarm:
  notification_all_calm:
  notification_smoke_detector:
  notification_juno:
  notification_motion_outside:
  notification_motion_toilet:
  notification_motion_workshop:
  notification_vacuum:
  notification_anniversary:
  notification_birthday:

#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:

# Reset Menu's after x Seconds (used with input_select on e.g. other view)
  - alias: 'reset input_select_richard'
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: input_select.general
    action:
    - delay:
        seconds: 20
    - service: input_select.select_option
      data:
        entity_id: input_select.general
        option: Home

  - alias: 'reset input_select_jess'
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: input_select.general2
    action:
    - delay:
        seconds: 20
    - service: input_select.select_option
      data:
        entity_id: input_select.general2
        option: Home

  - alias: 'reset main menu richard'
    initial_state: 'false'
    trigger:
    - platform: state
      entity_id: input_boolean.lovelace_menu_richard
      to: "on"
    action:
    - delay:
        seconds: 45
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.lovelace_menu_richard

  - alias: 'reset main menu jess'
    initial_state: 'false'
    trigger:
    - platform: state
      entity_id: input_boolean.lovelace_menu_jess
      to: "on"
    action:
    - delay:
        seconds: 45
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.lovelace_menu_jess

  - alias: 'reset input_select_vacuum'
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: input_select.vacuum
      to: 'Map'
      for:
        seconds: 30
    action:
    - service: input_select.select_option
      data:
        entity_id: input_select.vacuum
        option: Information