#################################################################
#                                                               #
#                       Packages/Vaccum                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                            Vacuum                             #
#                                                               #
#################################################################

vacuum:
  - platform: xiaomi_miio
    host: !secret albert_ip
    token: !secret albert_token
    name: Albert
    
#################################################################
#                                                               #
#                         Input Select                          #
#                                                               #
#################################################################

input_select:
  vacuum:
    name: Vacuum
    options:
      - Basic
      - Presets
      - Map
      - Information
    initial: Basic
  xiaomi_vacuum:
    name: Xiaomi Vacuum
    options:
      - Quiet
      - Balanced
      - Turbo
      - Max
      - Mop

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                  Template                        #
#                                                  #
####################################################

  - platform: template
    sensors:
      vacuum_battery:
        value_template: '{{ states.vacuum.albert.attributes.battery_level }}'
        friendly_name: 'Vacuum Battery Level'
        device_class: 'battery'
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_level = states('sensor.vacuum_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
      vacuum_total_cleaned_area:
        value_template: '{{ states.vacuum.albert.attributes.total_cleaned_area }}'
        friendly_name: 'Vacuum Total Cleaned Area'
      vacuum_cleaning_count:
        value_template: '{{ states.vacuum.albert.attributes.cleaning_count }}'
        friendly_name: 'Vacuum Cleaning Count'
      vacuum_total_cleaning_time:
        value_template: '{{ states.vacuum.albert.attributes.total_cleaning_time }}'
        friendly_name: 'Vacuum Total Cleaning Time'
      vacuum_main_brush_left:
        value_template: '{{ states.vacuum.albert.attributes.main_brush_left }}'
        friendly_name: 'Vacuum Main Brush Left'
      vacuum_side_brush_left:
        value_template: '{{ states.vacuum.albert.attributes.side_brush_left }}'
        friendly_name: 'Vacuum Side Brush Left'
      vacuum_filter_left:
        value_template: '{{ states.vacuum.albert.attributes.filter_left }}'
        friendly_name: 'Vacuum Filter Left'
      vacuum_sensor_dirty_left:
        value_template: '{{ states.vacuum.albert.attributes.sensor_dirty_left }}'
        friendly_name: 'Vacuum Sensor Dirty Left'
      vacuum_cleaner_error_sensor:
        friendly_name: Vacuum Cleaner Error Sensor
        value_template: >-
          {% if states.vacuum.albert.attributes.error is defined %}
            {{states.vacuum.albert.attributes.error}}
          {% else %}
            No Error
          {% endif %}
      vacuum_cleaner_status_sensor:
        friendly_name: Vacuum Cleaner Status Sensor
        value_template: >-
          {{ states.vacuum.albert.attributes.status }}

#################################################################
#                                                               #
#                         Automation                            #
#                                                               #
#################################################################

automation:

  - id: vacuum_cleaner_error
    alias: Vacuum Cleaner Error
    trigger:
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'Error'
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'In Error'
      - platform: state
        entity_id: sensor.vacuum_cleaner_status_sensor
        to: 'Charging Error'
    action:
      - service: notify.slack
        data:
          title: 'Albert'
          message: >-
            {% if is_state('sensor.vacuum_cleaner_error_sensor', 'No Error')  %}
              {{states.sensor.vacuum_cleaner_status_sensor.state}}
            {% else %}
              {{states.sensor.vacuum_cleaner_error_sensor.state}}
            {% endif %}

  - id: vacuum_cleaner_error_solved
    alias: Vacuum Cleaner Error Solved
    trigger:
      - platform: state
        entity_id: sensor.vacuum_cleaner_error_sensor
        to: 'No Error'
    action:
      - service: notify.slack
        data:
          title: 'Albert'
          message: Error Resolved

  - id: vacuum_cleaner_started
    alias: Vacuum Cleaner Started
    trigger:
      - platform: state
        entity_id: vacuum.albert
        to: 'cleaning'
      - platform: state
        entity_id: vacuum.albert
        to: 'returning'
      - platform: state
        entity_id: vacuum.albert
        to: 'docked'
      - platform: state
        entity_id: vacuum.albert
        to: 'paused'
      - platform: state
        entity_id: vacuum.albert
        to: 'idle'
    action:
      - service: notify.slack
        data:
          title: 'Albert'
          message: >-
            {{states.sensor.vacuum_cleaner_status_sensor.state}}

  - id: vacuum_fan_speed_balanced_when_docked
    alias: Vacuum Fan Speed Balanced When Docked
    trigger:
      - platform: state
        entity_id: vacuum.albert
        to: 'docked'
    action:
     - service: input_select.select_option
       data:
         option: Balanced
         entity_id: input_select.xiaomi_vacuum

  - id: vacuum_fan_speed_quiet
    alias: Vacuum Fan Speed Quiet
    trigger:
      - platform: state
        entity_id: input_select.xiaomi_vacuum
        to: 'Quiet'
    action:
     - service: vacuum.set_fan_speed
       data:
         entity_id: vacuum.albert
         fan_speed: 101

  - id: vacuum_fan_speed_balanced
    alias: Vacuum Fan Speed Balanced
    trigger:
      - platform: state
        entity_id: input_select.xiaomi_vacuum
        to: 'Balanced'
    action:
     - service: vacuum.set_fan_speed
       data:
         entity_id: vacuum.albert
         fan_speed: 102

  - id: vacuum_fan_speed_turbo
    alias: Vacuum Fan Speed Turbo
    trigger:
      - platform: state
        entity_id: input_select.xiaomi_vacuum
        to: 'Turbo'
    action:
     - service: vacuum.set_fan_speed
       data:
         entity_id: vacuum.albert
         fan_speed: 103

  - id: vacuum_fan_speed_max
    alias: Vacuum Fan Speed Max
    trigger:
      - platform: state
        entity_id: input_select.xiaomi_vacuum
        to: 'Max'
    action:
     - service: vacuum.set_fan_speed
       data:
         entity_id: vacuum.albert
         fan_speed: 104

  - id: vacuum_fan_speed_mop
    alias: Vacuum Fan Speed Mop
    trigger:
      - platform: state
        entity_id: input_select.xiaomi_vacuum
        to: 'Mop'
    action:
     - service: vacuum.set_fan_speed
       data:
         entity_id: vacuum.albert
         fan_speed: 105 