#################################################################
#                                                               #
#                      Packages/Workshop                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#                  Template                        #
#                                                  #
####################################################

  - platform: template
    sensors:
       motion_workshop_temperature:
        value_template: '{{ states.binary_sensor.workshop_presence.attributes.temperature }}'
        unit_of_measurement: '°C'
        friendly_name: Workshop Temperature

#################################################################
#                                                               #
#                           Switches                            #
#                                                               #
#################################################################

switch:

  - platform: wake_on_lan
    mac_address: "MAC_ADDRESS_HERE"
    name: PC
    host: "192.168.0.41"
    turn_off:
      service: hassio.addon_stdin
      data:
        addon: core_rpc_shutdown
        input: pc

#################################################################
#                                                               #
#                         Automation                            #
#                                                               #
#################################################################

automation:

  - alias: Smoke Alert
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: sensor.downstairs_nest_protect_smoke_status
    condition:
    - condition: template
      value_template: "{{ not is_state('sensor.downstairs_nest_protect_smoke_status', 'Ok') }}"
    action:
      - service: notify.slack
        data:
          title: "Smoke Detected"
          message: "There is smoke in the workshop!"